-- Adjustment to match total points EXACTLY
SET FOREIGN_KEY_CHECKS=0;
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 7, 99, 66);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 1, 99, 94);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 8, 99, 85);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 3, 99, 155);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 5, 99, 131);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 6, 99, 156);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 4, 99, 102);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 13, 99, 73);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 14, 99, 34);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 9, 99, 56);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 15, 99, 36);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 20, 99, 36);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 18, 99, 41);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 17, 99, 38);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 2, 99, 38);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 19, 99, 33);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 10, 99, 33);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 11, 99, 22);
INSERT INTO resultats (course_id, pilote_id, position, points) VALUES (24, 16, 99, 19);
SET FOREIGN_KEY_CHECKS=1;
